AllCops:
    TargetRubyVersion: 2.5
    NewCops: enable

Layout/IndentationWidth:
    Width: 4

Layout/LineLength:
    Enabled: true
    Max: 80

Metrics/MethodLength:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Lint/DuplicateMethods:
    Enabled: false

Style/MethodCallWithArgsParentheses:
    AllowParenthesesInMultilineCall: true
    AllowParenthesesInChaining: true
    AllowParenthesesInCamelCaseMethod: true
