sudo: false
language: ruby
cache: bundler

bundler_args: --without development

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'

before_install:
- gem install bundler
