name: Release package to rubygems.org

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
        env: 
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}

      - name: Build
        run: gem build *.gemspec

      - name: Publish
        run: gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
